export const quotes: string[] = [
    '“Dogs have Owners, Cats have Staff.”',
    '“I do not fear computers. I fear lack of them.” – Isaac Asimov',
    '“A computer once beat me at chess, but it was no match for me at kick boxing.” – Emo Philips',
    '“Computer Science is no more about computers than astronomy is about telescopes.” – Edsger W. Dijkstra',
    '“The computer was born to solve problems that did not exist before.” – Bill Gates',
    '“Software is like entropy: It is difficult to grasp, weighs nothing, and obeys the Second Law of Thermodynamics; i.e., it always increases.” – Norman Augustine',
    '“Software is a gas; it expands to fill its container.” – Nathan Myhrvold',
    '“All parts should go together without forcing. You must remember that the parts you are reassembling were disassembled by you. Therefore, if you can’t get them together again, there must be a reason. By all means, do not use a hammer.” – IBM Manual, 1925',
    '“Standards are always out of date. That’s what makes them standards.” – Alan Bennett',
    '“Physics is the universe’s operating system.” – Steven R Garman',
    '“It’s hardware that makes a machine fast. It’s software that makes a fast machine slow.” – Craig Bruce',
    '“Imagination is more important than knowledge. For knowledge is limited, whereas imagination embraces the entire world, stimulating progress, giving birth to evolution.” – Albert Einstein',
    '“The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge.” – Stephen Hawking',
    '“The more you know, the more you realize you know nothing.” – Socrates',
    '“Tell me and I forget. Teach me and I remember. Involve me and I learn.” – Benjamin Franklin',
    '“Real knowledge is to know the extent of one’s ignorance.” – Confucius',
    '“If people never did silly things, nothing intelligent would ever get done.” – Ludwig Wittgenstein',
    '“Getting information off the Internet is like taking a drink from a fire hydrant.” – Mitchell Kapor',
    '“If you think your users are idiots, only idiots will use it.” – Linus Torvalds',
    '“From a programmer’s point of view, the user is a peripheral that types when you issue a read request.” – P. Williams',
    '“Where is the ‘any’ key?” – Homer Simpson, in response to the message, “Press any key”',
    '“Computers are good at following instructions, but not at reading your mind.” – Donald Knuth',
    '“There is only one problem with common sense; it’s not very common.” – Milt Bryce',
    '“Your most unhappy customers are your greatest source of learning.” – Bill Gates',
    '“Let us change our traditional attitude to the construction of programs: Instead of imagining that our main task is to instruct a computer what to do, let us concentrate rather on explaining to human beings what we want a computer to do.” – Donald E. Knuth',
    '“The Internet? We are not interested in it.” – Bill Gates, 1993',
    '“The best way to get accurate information on Usenet is to post something wrong and wait for corrections.” – Matthew Austern',
    '“The most likely way for the world to be destroyed, most experts agree, is by accident. That’s where we come in; we’re computer professionals. We cause accidents.” – Nathaniel Borenstein',
    '“Pessimists, we’re told, look at a glass containing 50% air and 50% water and see it as half empty. Optimists, in contrast, see it as half full. Engineers, of course, understand the glass is twice as big as it needs to be.” – Bob Lewis',
    '“In a room full of top software designers, if two agree on the same thing, that’s a majority.” – Bill Curtis',
    '“It should be noted that no ethically-trained software engineer would ever consent to write a DestroyBaghdad procedure. Basic professional ethics would instead require him to write a DestroyCity procedure, to which Baghdad could be given as a parameter.” – Nathaniel S. Borenstein',
    '“Mostly, when you see programmers, they aren’t doing anything. One of the attractive things about programmers is that you cannot tell whether or not they are working simply by looking at them. Very often they’re sitting there seemingly drinking coffee and gossiping, or just staring into space. What the programmer is trying to do is get a handle on all the individual and unrelated ideas that are scampering around in his head.” – Charles M. Strauss',
    '“If you think you are worth what you know, you are very wrong. Your knowledge today does not have much value beyond a couple of years. Your value is what you can learn and how easily you can adapt to the changes this profession brings so often.” – Jose M. Aguilar',
    '“Programs must be written for people to read, and only incidentally for machines to execute.” – Abelson and Sussman',
    '“Commenting your code is like cleaning your bathroom : you never want to do it, but it really does create a more pleasant experience for you and your guests.” – Ryan Campbell',
    '“We have to stop optimizing for programmers and start optimizing for users.” – Jeff Atwood',
    '“Low-level programming is good for the programmer’s soul.” – John Carmack',
    '“It’s OK to figure out murder mysteries, but you shouldn’t need to figure out code. You should be able to read it.” – Steve McConnell',
    '“If we wish to count lines of code, we should not regard them as ‘lines produced’ but as ‘lines spent.’” – Edsger Dijkstra',
    '“Programming can be fun, so can cryptography; however they should not be combined.” – Kreitzberg and Shneiderman',
    '“Before software should be reusable, it should be usable.” – Ralph Johnson',
    '“If you automate a mess, you get an automated mess.” – Rod Michael',
    '“Looking at code you wrote more than two weeks ago is like looking at code you are seeing for the first time.” – Dan Hurvitz',
    '“The most disastrous thing that you can ever learn is your first programming language.” – Alan Kay',
    '“Any fool can write code that a computer can understand. Good programmers write code that humans can understand.” – Martin Fowler',
    '“The trouble with programmers is that you can never tell what a programmer is doing until it’s too late.” – Seymour Cray',
    '“A language that doesn’t affect the way you think about programming is not worth knowing.” – Alan Perlis',
    '“I think Microsoft named .Net so it wouldn’t show up in a Unix directory listing.” – Oktal',
    '“The most important property of a program is whether it accomplishes the intention of its user.” – C.A.R. Hoare',
    '“The best thing about a boolean is even if you are wrong, you are only off by a bit.” – Anonymous',
    '“To iterate is human, to recurse divine.” – L. Peter Deutsch',
    '“Java is to JavaScript what car is to Carpet.” – Chris Heilmann',
    '“Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday’s code.” – Dan Salomon',
    '“One of my most productive days was throwing away 1000 lines of code.” – Ken Thompson',
    '“Perl – The only language that looks the same before and after RSA encryption.” – Keith Bostic',
    '“There are two ways of constructing a software design: One way is to make it so simple that there are obviously no deficiencies, and the other way is to make it so complicated that there are no obvious deficiencies.” – C.A.R. Hoare',
    '“My software never has bugs. It just develops random features.” – Anonymous',
    '“The best method for accelerating a computer is the one that boosts it by 9.8 m/s².” – Anonymous',
    '“In order to understand recursion, one must first understand recursion.” – Anonymous',
    '“A good programmer is someone who always looks both ways before crossing a one-way street.” – Doug Linder',
    '“The beginning of wisdom is to acknowledge the fact that you know nothing.” – Socrates',
    '“The problem with quick and dirty, is that dirty remains long after quick has been forgotten.” – Steve C McConnell',
    '“When debugging, novices insert corrective code; experts remove defective code.” – Richard Pattis',
    '“Walking on water and developing software from a specification are easy if both are frozen.” – Edward V Berard',
    '“If debugging is the process of removing software bugs, then programming must be the process of putting them in.” – Edsger Dijkstra',
    '“It’s not a bug – it’s an undocumented feature.” – Anonymous',
    '“The trouble with programmers is that you can never tell what a programmer is doing until it’s too late.” – Seymour Cray',
    '“Most software isn’t designed. Rather, it emerges from the developer’s head as a series of small, often irreversible decisions.” – David Parnas',
    '“Good code is its own best documentation. As you’re about to add a comment, ask yourself, How can I improve the code so that this comment isn’t needed?” – Steve McConnell',
    '“The first 90% of the code accounts for the first 90% of the development time. The remaining 10% of the code accounts for the other 90% of the development time.” – Tom Cargill',
    '“If the code and the comments do not match, possibly both are incorrect.” – Norm Schryer',
    '“Measuring programming progress by lines of code is like measuring aircraft building progress by weight.” – Bill Gates',
    '“Any sufficiently advanced bug is indistinguishable from a feature.” – Rich Kulawiec',
    '“There are only two kinds of programming languages: those people always bitch about and those nobody uses.” – Bjarne Stroustrup',
    '“Don’t worry if it doesn’t work right. If everything did, you’d be out of a job.” – Mosher’s Law of Software Engineering',
    '“I don’t care if it works on your machine! We are not shipping your machine!” – Vidiu Platon',
    '“The best thing about a boolean is even if you are wrong, you are only off by a bit.” – Anonymous',
    '“Without requirements or design, programming is the art of adding bugs to an empty text file.” – Louis Srygley',
    '“The hardest part of design … is keeping features out.” – Donald Norman',
    '“The perfect project plan is possible if one first documents a list of all the unknowns.” – Bill Langley',
];
